### ISSUE TITLE
[BUG] addWeeklyRecurringAvailability

### ISSUE THREAD

**Issue by klinkert0728** [fubar/availability-schedule#1]
Add weekly Recurring availability is not working 

<img width="567" alt="Screen Shot 2019-07-12 at 9 38 33 AM" src="https://user-images.githubusercontent.com/6820828/61136491-6399a800-a489-11e9-907b-65ce24d67e5b.png">

**Comment by fubar** [comment]
Hi @klinkert0728, this isn't enough info to give me insight into what's failing. Can you provide a code sample that I can run to reproduce the issue? Also your node version. Thanks!

**Comment by fubar** [comment]
Stale issue, closing.

**Comment by klinkert0728** [comment]
sorry for the late response, I did not get the notification about your comment 🙈
