### ISSUE TITLE
[Suggestion] Option to add additional data to recurring schedule

### ISSUE THREAD

**Issue by neilspaul** [fubar/availability-schedule#4]
Been working with availability-schedule for a few days now. Really great package to work with schedules.
It would be great if there is an option to add any additional data to the availability

For example, number of slots available in a time start and end time.

Thanks

**Comment by fubar** [comment]
Hi Neil, glad to hear you find this library useful. The purpose of this library is to help with time schedules, and I want to keep it focused on that. It is small and simple, which means it's very extensible. If by slots you mean multiple parallel availabilities - such as multiple meeting rooms - you would have to create one instance of the schedule per room and tally up available instances (rooms) for a given time slot. If however you want to limit the time that can be booked, that would be the responsibility of your booking logic and UI layer. Similarly, this library doesn't store anything, and you would have to store any additional data with the records you store for meetings or availabilities that you feed into this library.

Hope that helps!
